#Project: The "86-List" Inventory Manager
#Focus: changed from hard coded dict to menu.csv file
#Focus: Permanent Record keeping. generates audit_history.log, shopping_list.txt, shopping_list_YYYY-MM-DD.csv
#New Feature: Function Separation: The logic is no longer one giant "main" function. It is split into load_inventory_from_menu, run_inventory_audit, and print_audit_report.
#New Feature: creates a seamless bridge between your POS and your Audit. It now attempts to find sales_today.json first. If it finds the file, it auto-fills the "Units Sold" for the manager; if the file is missing, it gracefully falls back to asking the manager manually.


import csv  # Provides functionality for reading and writing Comma Separated Value files
import sys  # Provides access to system-specific parameters and functions like sys.exit()
import json # Provides tools to parse and read the JSON sales data from the POS system
from datetime import datetime  # Provides classes for manipulating dates and times
from validator import get_int  # Imports your custom integer validation tool from validator.py

# =================================================================
# PHASE 1: CUSTOM EXCEPTIONS & DATA LOADING
# =================================================================

class InventoryError(Exception):
    """Custom exception class to handle business-logic errors during inventory counts."""
    pass # This inherits from the base Exception class without adding new behavior

def load_inventory_from_menu(filename="menu.csv"):
    """Reads the master inventory data, prices, and par levels from a CSV file."""
    inventory_list = []  # Initialize an empty list to store dictionary objects for each item
    try:
        # Open the CSV file in read mode with UTF-8 encoding to prevent character errors
        with open(filename, mode="r", newline="", encoding="utf-8") as file:
            reader = csv.DictReader(file)  # Create a reader that maps header row to keys
            for row in reader:  # Iterate through every row (item) in the spreadsheet
                # Convert string-based CSV data into numeric types for calculations
                row["unit_price"] = float(row["unit_price"])  # Convert price to decimal (float)
                row["line_inv"] = int(row["line_inv"])        # Convert line count to integer
                row["walk_in_inv"] = int(row["walk_in_inv"])  # Convert walk-in count to integer
                row["freezer_inv"] = int(row["freezer_inv"])  # Convert freezer count to integer
                row["par_level"] = int(row["par_level"])      # Convert par level to integer
                # Feature 6: Pre-calculate total building stock available at shift start
                row["starting_inv"] = row["line_inv"] + row["walk_in_inv"] + row["freezer_inv"]
                inventory_list.append(row)  # Append the processed dictionary to the list
        return inventory_list  # Return the list of menu items to the calling function
    except FileNotFoundError:  # Handle the error if the menu.csv file is missing
        print("❌ Error: menu.csv not found.")  # Inform the user of the specific error
        sys.exit()  # Terminate the program safely to avoid further errors

def load_sales_data(filename="sales_today.json"):
    """NEW: Loads the units sold recorded by digitalpos.py during the shift."""
    try:
        # Attempt to open the JSON file generated by the POS system
        with open(filename, "r") as f:
            return json.load(f)  # Convert JSON string into a Python dictionary
    except (FileNotFoundError, json.JSONDecodeError):
        # If the POS hasn't run yet or the file is corrupted, return an empty dict
        return {}  # Allows the script to proceed without crashing

# =================================================================
# PHASE 2: PROCESSING (THE "INPUT" LOOP)
# =================================================================

def run_inventory_audit():
    """Main logic loop for manager data entry, validation, and math processing."""
    inventory = load_inventory_from_menu()  # Call the loader to get menu data
    sales_data = load_sales_data()          # Call the loader to get POS sales totals
    
    # Storage container dictionary to collect data for the final reporting function
    audit_results = {
        "shrinkage": [],    # List of items where units went missing (Feature 6)
        "waste": [],        # List of items recorded as waste/comps (Feature 6)
        "prep": [],         # List of items requiring a pull from storage (Feature 7)
        "shopping": [],     # List of items that must be bought externally (Feature 7)
        "total_sold_val": 0.0,  # Accumulator for actual net revenue (Feature 5)
        "total_waste_val": 0.0, # Accumulator for financial loss due to waste
        "total_shrink_val": 0.0 # Accumulator for financial loss due to shrinkage
    }

    # Print a professional header for the manager's audit session
    print("\n" + "="*60)
    print(f"{'NIGHTLY MANAGER AUDIT ENTRY':^60}")
    print("="*60)

    for item in inventory:  # Process every menu item one by one
        print(f"\n📝 RECORDING: {item['name'].upper()}")  # Display the current item name
        
        # Check if the POS sales dictionary has a record for this specific item
        pos_sold = sales_data.get(item['name'], 0)  # Default to 0 if item wasn't sold
        
        if pos_sold > 0:  # If the POS reports sales, display it for the manager
            print(f"  [ POS reports {pos_sold} units sold ]")
        
        print(f"  [ Morning Start: {item['starting_inv']} ]")  # Display initial total stock

        # Feature 1: Loop for current item until data entry passes all logical checks
        while True: 
            try:
                # Feature 2 & 4: Safe numeric input; POS data is used as the suggested default
                sold = get_int(f"  Units SOLD (Confirm POS {pos_sold}): ", min_val=0, allow_zero=True)
                waste = get_int(f"  Units WASTED/COMPED: ", min_val=0, allow_zero=True)
                physical = get_int(f"  FINAL PHYSICAL COUNT: ", min_val=0, allow_zero=True)

                # Feature 3: FAT FINGER GUARDRAIL - Verification prompt for high numbers
                if sold > 100 or waste > 100 or physical > 100:
                    confirm = input(f"  ⚠️  {max(sold, waste, physical)} seems high. Confirm? (y/n): ").lower()
                    if confirm != 'y': continue  # Restart the 'while' loop for this item

                # Feature 6: IMPOSSIBLE COUNT EXCEPTION - Prevents entering more than existed
                if (sold + waste + physical) > item['starting_inv']:
                    # Raise custom exception to stop the logic and force a re-entry
                    raise InventoryError(f"Math Error: You only started with {item['starting_inv']} {item['name']}.")
                
                # Feature 5: FINANCIAL MATH - Calculate dollar value of sold units
                item_sales_val = sold * item["unit_price"]  # Price times units sold
                audit_results["total_sold_val"] += item_sales_val  # Add to the shift's net total
                
                # WASTE TRACKING: Process items intentionally removed from inventory
                if waste > 0:
                    waste_loss = waste * item["unit_price"]  # Calculate value of wasted stock
                    audit_results["total_waste_val"] += waste_loss  # Add to total waste accumulator
                    # Append data to waste list for the final report table
                    audit_results["waste"].append({"name": item['name'], "qty": waste, "loss": waste_loss, "base_sales": item_sales_val})

                # SHRINKAGE MATH: Detect unexplained inventory loss (Feature 6)
                expected = item["starting_inv"] - sold - waste  # Calculated amount that SHOULD be left
                if physical < expected:  # If reality is less than calculation...
                    missing = expected - physical  # Calculate the exact gap
                    shrink_loss = missing * item["unit_price"]  # Calculate the financial loss
                    audit_results["total_shrink_val"] += shrink_loss  # Add to shrink accumulator
                    # Append data to shrinkage list for the final report table
                    audit_results["shrinkage"].append({"name": item['name'], "qty": missing, "loss": shrink_loss, "base_sales": item_sales_val})
                
                # Feature 7: PREP vs SHOPPING LOGIC - Location-aware stock management
                if physical < item["par_level"]:  # Check if physical stock is below 'safety' par
                    shortage = item["par_level"] - physical  # Calculate the total units needed
                    # If storage locations have enough to cover the need, it is a 'Prep' task
                    if (item["walk_in_inv"] + item["freezer_inv"]) >= shortage:
                        audit_results["prep"].append({"name": item['name'], "qty": shortage})
                    # If the whole building is out of stock, it is a 'Shopping' task
                    else:
                        audit_results["shopping"].append({"name": item['name'], "qty": shortage})

                break  # Exit the 'while' loop; input is clean and logic is satisfied
            except InventoryError as e:  # Catch the custom exception if it was raised
                print(f"  ❌ {e} Please re-enter counts.")  # Print the error message to the user

    # Hand off the final collected results to the modular Reporting function
    print_audit_report(audit_results)
    return audit_results["total_sold_val"]

# =================================================================
# PHASE 3: REPORTING (THE "OUTPUT")
# =================================================================

def print_audit_report(results):
    """Handles the UI display, permanent history logging, and CSV list generation."""
    now = datetime.now()  # Capture the current date and time
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")  # Format for history log entry
    file_date = now.strftime("%Y-%m-%d")  # Format for unique CSV file naming

    # FINANCIAL SUMMARY CALCULATIONS (Feature 4 + Potential Revenue)
    total_net = results["total_sold_val"]  # Actual revenue from units sold
    # Potential revenue is Net + Waste + Shrink (Total value of used/lost goods)
    potential = total_net + results["total_waste_val"] + results["total_shrink_val"]
    
    # Output the primary financial table to the terminal
    print("\n\n" + "="*60)
    print(f"{'OFFICIAL AUDIT & REVENUE REPORT':^60}")
    print(f"{timestamp:^60}")
    print("="*60)

    print(f"\n[{'SHIFT REVENUE':^25}]")
    print(f"  TOTAL NET SALES (SOLD):         ${total_net:>12.2f}")
    print(f"  TOTAL WASTE VALUE:              ${results['total_waste_val']:>12.2f}")
    print(f"  TOTAL SHRINKAGE LOSS:           ${results['total_shrink_val']:>12.2f}")
    print(f"  TOTAL POTENTIAL REVENUE:        ${potential:>12.2f}")

    # Display the Shrinkage Breakdown table (Feature 5 & 6)
    print("\n" + "="*75)
    print(f"{'SHRINKAGE BREAKDOWN':<25} | {'QTY':>5} | {'LOSS $':>10} | {'% OF ITEM SALES'}")
    print("-" * 75)
    if results["shrinkage"]:  # Only print if shrinkage items exist
        for s in results["shrinkage"]:
            # Calculate what % the loss represents relative to actual sales for that item
            s_pct = (s['loss'] / s['base_sales'] * 100) if s['base_sales'] > 0 else 100.0
            print(f"{s['name']:<25} | {s['qty']:>5} | ${s['loss']:>9.2f} | {s_pct:>14.1f}%")
    else:  # Inform the manager if all inventory matches perfectly
        print("  ✅ All physical units accounted for.")

    # Display the Waste/Comp Log table (Feature 6)
    print("\n" + "="*75)
    print(f"{'WASTE & COMPS LOG':<25} | {'QTY':>5} | {'LOSS $':>10} | {'% OF ITEM SALES'}")
    print("-" * 75)
    if results["waste"]:  # Only print if waste items exist
        for w in results["waste"]:
            # Calculate waste as a percentage of that item's revenue
            w_pct = (w['loss'] / w['base_sales'] * 100) if w['base_sales'] > 0 else 100.0
            print(f"{w['name']:<25} | {w['qty']:>5} | ${w['loss']:>9.2f} | {w_pct:>14.1f}%")
    else:  # Inform the manager if no waste was recorded
        print("  ✅ No waste reported.")

    # Display the Kitchen Prep List (Feature 7)
    print("\n" + "="*45)
    print(f"{'KITCHEN PREP LIST':<30} | {'QTY':>5}")
    print("-" * 45)
    for p in results["prep"]: print(f"{p['name']:<30} | {p['qty']:>5}")

    # PERMANENT LOGGING: Save a summary of this shift to the audit_history.log file
    with open("audit_history.log", "a", encoding="utf-8") as f:
        # Append mode ('a') ensures we don't overwrite previous days' data
        f.write(f"\n[{timestamp}] REV: ${total_net:.2f} | SHRINK: ${results['total_shrink_val']:.2f}\n")

    # FEATURE 7: Generate a unique CSV Shopping List for external ordering
    if results["shopping"]:  # Only create the file if there is something to buy
        csv_name = f"shopping_list_{file_date}.csv"  # Name the file with today's date
        with open(csv_name, "w", newline="") as f:  # Open file in write mode ('w')
            writer = csv.writer(f)  # Create a CSV writer object
            writer.writerow(["Item", "Qty to Order"])  # Write the header row
            for s in results["shopping"]:  # Iterate through the shopping results
                writer.writerow([s['name'], s['qty']])  # Write the name and quantity as a row
        print(f"\n✅ CSV Shopping List generated: {csv_name}")  # Notify the manager

# Standard Python check: Run the audit logic only if this script is executed directly
if __name__ == "__main__":
    run_inventory_audit()  # Execute the main function to start the manager audit
